### ISSUE TITLE
Support converting CloudFormation templates to Terraform HCL

### ISSUE THREAD

**Issue by cristim** [kvz/json2hcl#5]
There should be a way to automate the conversion of the JSON/YAML CloudFormation template code into HCL, at least to a degree that would cover some 80-90% of the template code then the rest should be doable by a human.

- Many resources are relatively portable, for example field names are CamelCaseWords in CloudFormation and underscore_separated_words in Terraform but the content would often convert cleanly.
- stack parameters should be converted into variables and stored under variables.tf
- outputs should be converted into terraform outputs and stored under outputs.tf
- the intrinsic functions should be converted into the similar terraform constructs whenever possible, but it's okay to not make a perfect conversion where it would be hard to do. Just comment them as TODOs to make them visible and let the user finish the conversion.

**Comment by kvz** [comment]
Hi,

Thanks for the suggestion! Even though we use terraform in our examples and it's a great usecase, hcl can be used for many things and it's beyond the scope of this tool to provide much boilerplate towards compatibility with competing terraform platforms.

As a tip: Since we're just a wrapper around hashicorp's hcl libraries, perhaps the best way to create a tool like you describe is to create a similar wrapper geared towards your goals.

Good luck and have a nice weekend!

**Comment by cristim** [comment]
Thanks, I'll give this a try.
